### ISSUE TITLE
Output "rebar3_sheldon analysis starting, this may take a while..." at the start of execution

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [vkatsuba/rebar3_sheldon#30]
## `rebar3_sheldon` version

[0.4.2](https://github.com/vkatsuba/rebar3_sheldon/tree/0.4.2)

## `OS` version

macOS 13.5.1

## Description
* **Motivation**

`rebar3_sheldon` tends to be slow (haven't analysed it this is an issue with implementation or the sheer volume of stuff it has to deal with).

* **Proposal**

Give the consumer a notice about the plugin taking a while to load/execute.

## Current behavior

`rebar3_sheldon` runs with no indication of "taking a long time".

## Expected behavior

`rebar3 sheldon` should output (when starting) something like "rebar3_sheldon analysis starting, this may take a while...` as is common for other plugins, e.g. `dialyzer` or `rebar3_lint`.

## Config

None available.

**Comment by vkatsuba** [comment]
Thanks for open this issue. Will add it to plugin. The slow work of  Sheldon library is related to point that during run application it try prepare a text module based on dictionaries and provide some index of words for spellcheck. This take a some time. Totally, need to improve it.

**Comment by paulo-ferraz-oliveira** [comment]
I can also add it (should be fairly simple, I hope) if you're outta time. Lemme know 👍

**Comment by vkatsuba** [comment]
Any contribution to the project are welcome. If you have a time, please, prepare PR with changes and I will accept it ASAP after review.
